# lightning.pytorch==2.5.0
trainer:
  max_epochs: 50
  check_val_every_n_epoch: 1
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: ./checkpoints/fusion/four-stream/lightning_logs
model:
  in_channels: 1
  classes: 1
  total_epochs: 50
data:
  data_dir: data/train_val/
  test_dir: data/test/
  indices_dir: data/indices/
  select_frame_method: specific
dl_classification_mode: BINARY_CLASS_3_MODE
eval_classification_mode: BINARY_CLASS_3_MODE
image_loading_mode: GREYSCALE

